// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwnSrlIn1Pa94K6XTLW5D_keYoMNTfnsc',
    appId: '1:753214104858:web:3540e27f6038ccdac838a3',
    messagingSenderId: '753214104858',
    projectId: 'mynotes-fluttercourse-project1',
    authDomain: 'mynotes-fluttercourse-project1.firebaseapp.com',
    storageBucket: 'mynotes-fluttercourse-project1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Ajt_MHYW_qCBrFz7L28mYF19WHUMdME',
    appId: '1:753214104858:android:28c7037bebbf7f51c838a3',
    messagingSenderId: '753214104858',
    projectId: 'mynotes-fluttercourse-project1',
    storageBucket: 'mynotes-fluttercourse-project1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCawYAYc55qm33RcV2qnQlCI4lTsIwjrSk',
    appId: '1:753214104858:ios:2c7b9f2a2515da77c838a3',
    messagingSenderId: '753214104858',
    projectId: 'mynotes-fluttercourse-project1',
    storageBucket: 'mynotes-fluttercourse-project1.appspot.com',
    iosClientId:
        '753214104858-jij95q06c0tpbeasbot09un6jsiop3ki.apps.googleusercontent.com',
    iosBundleId: 'studio.desygn.mynotes',
  );
}
